<?php declare(strict_types=1);
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

 use Magmodules\FeedbackCompanySR\Block\Widget\Review\Textual;
 use Magento\Framework\Escaper;

/** @var Textual $block */
/** @var Escaper $escaper */

$uniqId = $block->getUniqueId();
$reviewsCount = $block->getReviewsCount();
$reviewsCurrentRating = $block->getReviewsCurrentRating();
$reviewsMaxRating = $block->getReviewsMaxRating();

$reviewsLabel = $reviewsCount > 1 ? __('%1 reviews', $reviewsCount) : __('%1 review', $reviewsCount);
?>

<section data-element="feedbackcompany-textual-widget-<?= $uniqId; ?>"
         class="inline-flex items-center flex-wrap gap-3 px-3 py-2
              bg-white border border-gray-200 shadow rounded-xl">
    <?php if ($block->showIcons()): ?>
        <img src="<?= $escaper->escapeUrl($block->getSmallLogoUrl()); ?>" width="24" height="24"
             alt="<?= $escaper->escapeHtml(__('Feedback Company textual widget')); ?>" />
    <?php endif;?>

    <?php if ($block->showStars()): ?>
        <?= $block->getLayout()
                ->createBlock('Magento\Framework\View\Element\Template')
                ->setTemplate('Magmodules_HyvaFeedbackCompanySR::widget/helper/stars.phtml')
                ->setData('svgSize', '22')
                ->setData('percent', $reviewsCurrentRating / $reviewsMaxRating * 100)
                ->toHtml();
        ?>
    <?php endif;?>

    <div class="text pt-0.5 text-sm text-gray-700">
        <?= $escaper->escapeHtml(__('Our store is rated with a <b>%1</b> based on <b>%2</b>', $reviewsCurrentRating, $reviewsLabel), ['b']); ?>
    </div>
</section>
